import turtle
wn = turtle.Screen()             # Set up the window and its attributes
wn.bgcolor("lightgreen")

alex=turtle.Turtle()
alex.pensize(7)
alex.speed(5)
alex.penup()
alex.forward(-200)
alex.pendown()
d=100
color=['red','green','blue','pink','black','violet','brown','red','green']

arpi=turtle.Turtle()
arpi.pensize(5)
arpi.penup()
arpi.forward(200)
arpi.pendown()
distance=10
arpii=turtle.Turtle()
arpii.pensize(5)
arpii.penup()
arpii.forward(200)
arpii.pendown()
arpii.color('red')
for _ in range(20):
    arpi.forward(distance)
    arpi.right(90)
    distance=distance+5
    arpii.forward(distance)
    arpii.right(90)

arpiii=turtle.Turtle()
arpiii.pensize(30)
arpiii.penup()
arpiii.forward(200)
arpiii.left(90)
arpiii.forward(90)
arpiii.pendown()
arpiii.forward(70)
arpiii.left(35)
arpiii.forward(60)
arpiii.color('gray')
arpiii.forward(-60)
arpiii.right(60)
arpiii.forward(60)

arp=turtle.Turtle()
arp.pensize(10)
arp.shape('square')
arp.speed(3)
dis=45
arp.penup()
arp.forward(200)
arp.right(90)
arp.forward(200)
arp.pendown()
for a in range(5):
    arp.stamp()
    arp.left(90)
    arp.forward(dis)
    arp.left(90)
    arp.forward(80)
    arp.color(color[a])
    arp.forward(-80)
    arp.left(90)
    arp.forward(dis*2)
    arp.right(90)
    arp.forward(80)
    arp.forward(-80)
    arp.right(90)
    arp.forward(dis)
    arp.right(90)
    dis=dis-5

a=turtle.Turtle()
a.penup()
a.forward(100)
a.pendown()
a.left(90)
a.forward(500)
a.forward(-1000)

elen=turtle.Turtle()
elen.shape('turtle')
elen.pensize(13)
elen.speed(1)
elen.penup()
elen.forward(-200)
elen.forward(1)
elen.left(90)
elen.forward(150)
elen.pendown()
elen.right(30)
elen.forward(75)
elen.right(120)
elen.forward(130)
elen.color('red')
elen.forward(-80)
elen.right(120)
elen.forward(70)
elen.color('blue')
elen.forward(-70)
elen.left(120)
elen.forward(50)
elen.left(60)

for i in range(21):
    alex.left(45)
    alex.forward(d)
    alex.right(90)
    alex.forward(d)
    alex.left(45)
    alex.left(45)
    alex.forward(d)
    alex.right(90)
    alex.forward(d)
    alex.right(90)
    alex.forward(d*2)
    alex.right(90)
    alex.forward(d*2)
    alex.right(135)
    alex.a='happy birthday ARPIII,wish num'
    print(alex.a,i)
    d=d-1

    if i==5:
        elen.penup()
        elen.forward(15)
        elen.pendown()

        elen.left(90)
        elen.forward(90)
        elen.right(90)
        elen.forward(40)
        elen.right(90)
        elen.forward(30)
        elen.right(90)
        elen.forward(40)
        elen.left(120)
        elen.color('black')
        elen.forward(90)
        elen.color('purple')
        elen.forward(-30)
        elen.left(60)
    if 5<i<15:
        alex.color(color[0])



    if i==10:
        elen.penup()
        elen.forward(30)
        elen.pendown()

        elen.color('purple')
        elen.left(90)
        elen.forward(80)
        elen.right(90)
        elen.forward(40)
        elen.right(90)
        elen.forward(30)
        elen.right(90)
        elen.forward(40)
        elen.color('green')
        elen.left(90)
        elen.forward(70)
        elen.color('gray')
        elen.forward(-20)
        elen.left(90)
    if 10<i<15:
        alex.color(color[2])


    if i==15:
        elen.penup()
        elen.forward(56)
        elen.pendown()
        elen.forward(60)
        elen.forward(-30)
        elen.stamp()
        elen.left(90)
        elen.forward(80)
        elen.right(90)
        elen.forward(30)
        elen.forward(-60)
        elen.forward(30)
        elen.stamp()
        elen.right(90)
        elen.color('red')
        elen.forward(80)
        elen.left(90)
        elen.forward(30)
    if 15<i<20:
        alex.color(color[1])
wn.exitonclick()
